# fly.toml app configuration file generated for medlab-backend on 2026-05-12T18:20:42+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medlab-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  EMAIL_FROM = 'Family Care MedLab <noreply@familycare.com>'
  JWT_EXPIRES_IN = '7d'
  NODE_ENV = 'production'
  PORT = '8080'
  SMTP_HOST = 'smtp.gmail.com'
  SMTP_PORT = '587'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
